config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home_pages#index'
  resources :notes, except: %i[destroy new]
  resources :home_pages, only: %i[index show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/filterable.rb
# frozen_string_literal: true
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params, user = nil)
      results = where(nil)
      results = results.where(user:) if method_defined?(:user) && user
      return results.order(created_at: :desc) if filtering_params.blank?

      value = filtering_params.values.first
      key = filtering_params.keys.first
      results.public_send("filter_#{key}", value) if value.present?
    end
  end
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  include Filterable
  belongs_to :user
  validates_presence_of :title, :body, :note_date
  validate :valid_date?, unless: :date_presence?
  belongs_to :author, foreign_key: :user_id, class_name: 'User'


  scope :filter_sort_by_name, ->(value) { order("#{value} ASC") }
  scope :filter_search, ->(value) { where( "title ILIKE :search OR body ILIKE :search", search: "%#{value.downcase}%") }

  def date_presence?
    note_date.blank?
  end

  def valid_date?
    return unless Date.today > note_date

    errors.add(:note_date, "can't be in the past")
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def selected_params
    @selected_params = params.slice(:sort_by_name, :search)
  end
end

app/controllers/home_pages_controller.rb
# frozen_string_literal: true

class HomePagesController < ApplicationController
  before_action :set_note, only: [:show]
  before_action :selected_params, only: [:index]

  def index
    @notes = Note.filter(@selected_params)
  end

  def show; end

  private

  def set_note
    @note = Note.find(params[:id])
  end

end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :authenticate_user!
  before_action :set_note, only: %i[show update edit]
  before_action :selected_params, only: [:index]
  def index
    @note = Note.new
    @notes = Note.filter(@selected_params, current_user)
  end

  def show; end

  def edit; end

  def create
    @note = current_user.notes.build(note_params)

    if @note.save
      streams = []
      streams << turbo_stream.prepend('notes', partial: 'notes/note', locals: { note: @note })
      streams << turbo_stream.replace('note_form', partial: 'notes/form', locals: { note: Note.new })
      render turbo_stream: streams
    else
      render turbo_stream: turbo_stream.replace('error_message', partial: 'shared/error_message',
                                                                 locals: { message: @note.errors.full_messages.to_sentence })
    end
  end

  def update
    streams = []
    if @note.update(note_params)
      streams << turbo_stream.replace('edit_card', partial: 'full_note', locals: { note: @note })
      streams << turbo_stream.replace(dom_id(@note).to_s, partial: 'note', locals: { note: @note })
    else
      streams << turbo_stream.replace('error_message', partial: 'shared/error_message',
                                                       locals: { message: @note.errors.full_messages.to_sentence })
    end

    render turbo_stream: streams
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:body, :title, :note_date)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def resource_name
    :user
  end

  def resource_class
    User
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/home_pages_helper.rb
# frozen_string_literal: true

module HomePagesHelper
  def blue_btn
    'btn btn-primary'
  end

  def green_btn
    'btn btn-success'
  end

  def red_btn
    'btn btn-danger'
  end

  def f_label
    'form-label'
  end

  def f_control
    'form-control'
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  def can_edit_note?(note)
    user_signed_in? && note.author == current_user
  end
end

app/views/home_pages/_card.html.erb
<div class="col">
  <div class="card" >
    <div class="card-body">
      <h5><%= link_to note.title, home_page_path(note) %></h5>
      <p class="card-text text-truncate m-0"><%= note.body %></p>
    </div>
    <div class="card-footer">
      <small class="text-muted"><%= note.note_date %></small>
    </div>
  </div>

</div>

app/views/home_pages/index.html.erb
<div class="row row-cols-1 row-cols-md-4 g-4">
  <%= render 'notes/search_bar', locals: { path: home_pages_path } %>
  <%= render 'notes/order_notes' %>
  <% @notes.each do |note| %>
    <%= render 'card', note: note %>
  <% end %>
</div>

app/views/home_pages/show.html.erb
<%= render 'notes/full_note', note: @note %>
<%= link_to 'Back', root_path, class: green_btn %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyectoNotas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <%= turbo_frame_tag 'error_message' %>
  <div class="app__container px-5">
    <%= yield %>
  </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with model: note, id: "note_form" do |f| %>
  <div class="mb-3">
    <%= f.label :title, class: f_label %>
    <%= f.text_field :title, class: f_control %>
  </div>
  <div class="mb-3">
    <%= f.label :body, class: f_label %>
    <%= f.text_area :body, class: f_control %>
  </div>
  <div class="mb-3">
    <%= f.label :note_date, class: f_label %>
    <%= f.date_field :note_date, class: f_control %>
  </div>

  <%= f.submit 'Post', class: green_btn %>
<% end %>

app/views/notes/_full_note.html.erb
<%= turbo_frame_tag 'edit_card' do %>
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= note.title %></h5>
    <p class="card-text lh-lg body__text"><%= note.body %></p>
    <footer class="blockquote-footer mt-2 text-end"><%= note.author.email %> <cite title="Source Title"><%= note.note_date %></cite></footer>
  </div>
  <% if can_edit_note?(note) %>
    <%= link_to 'Edit', edit_note_path(note), class: blue_btn %>
  <% end %>
</div>
<% end %>

app/views/notes/_note.html.erb
<div class="card mb-3" style="width: 18rem;" id="<%= dom_id note %>">
    <div class="card-header">
      <%= link_to note.title, note_path(note), data: {
        turbo_frame: 'full_note'
      }, class: 'text-decoration-none' %>
    </div>
  <div class="card-body">
    <p class="card-text text-truncate m-0"><%= note.body %></p>
    <p class="card-text m-0 text-end"><%= note.note_date %></p>
  </div>
</div>

app/views/notes/_order_notes.html.erb
<div class="filter__container" style="width: 18rem;">
  <div class="card-body card__filter" >
    <h5 class="card-title">Order by:</h5>
    <div class="btn-group">
      <%= link_to "Title", { sort_by_name: "title" }, class: green_btn %>
      <%= link_to "Date", { sort_by_name: "note_date" }, class: green_btn %>
    </div>
  </div>
</div>

app/views/notes/_search_bar.html.erb
<%= form_tag(locals[:path], method: :get, class: 'search__bar row g-3') do %>
  <div class="col-auto">
    <%= text_field_tag(:search, params[:search], placeholder: 'Search by Title or Content', class: 'form-control') %>
  </div>
  <div class="col-auto">
    <%= submit_tag("Search", class: blue_btn, method: :get) %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<%= turbo_frame_tag 'edit_card' do %>
  <%= render 'form', note: @note %>
  <%= link_to 'Cancel', note_path(@note), class: blue_btn %>
<% end %>

app/views/notes/index.html.erb
<%= render 'search_bar', locals:{ path: notes_path } %>
<div class="note__container">
    <div class="">
      <%= render 'form', note: @note %>
    </div>
    <div class="all__notes">
      <%= render 'order_notes' %>
      <%= turbo_frame_tag 'notes' do %>
         <%= render @notes %>
      <% end %>
    </div>
    <div class="full__note__container">
        <%= turbo_frame_tag "full_note" %>
    </div>
</div>

app/views/notes/show.html.erb
<%= turbo_frame_tag "full_note" do %>
  <%= render "full_note", note: @note %>
<% end %>

app/views/shared/_error_message.html.erb
<%= turbo_frame_tag 'error_message' do %>
  <div data-controller="error-message" class="error__message py-2">
      <div class="mx-2">
          <%= message %>
      </div>
    <%= link_to '','', data: {
      controller: 'error-message',
      action: 'error-message#close_error_message'
    },
    class: 'btn-close mx-2'%>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid px-4">
    <div>
      <%= link_to 'Home', root_path, class: "navbar-brand" %>
      <%= link_to 'Notes', notes_path, class: 'navbar-brand' %>
    </div>
    <% if user_signed_in? %>
      <div class="d-flex">
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: red_btn %>
      </div>
    <%else %>
      <div class="d-flex nav__container--session justify-content-between">

        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            Sign In
          </button>
          <ul class="dropdown-menu " aria-labelledby="dropdownMenuButton1">
            <%= render 'devise/sessions/new_session' %>
          </ul>
        </div>

        <%= link_to 'Registration', new_user_registration_path, class: blue_btn %>
      </div>
    <% end %>

  </div>
</nav>